[package]
name = "axum"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
axum = "0.6.20"
markup = { path = "../../markup" }
serde = { version = "1.0.192", features = ["derive"] }
tokio = { version = "1.34.0", features = ["full"] }
