name: Benchmark

on: [push, pull_request]

jobs:
  benchmark:
    name: ${{ matrix.os }} - ${{ matrix.rust }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        rust: [stable, nightly]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
      - run: git checkout HEAD~1
      - run: cargo bench
      - run: git checkout -
      - run: cargo bench
      - run: cargo bench --features itoa
