name: Build

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.os }} - ${{ matrix.rust }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        rust: [stable, nightly, 1.56.1]
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
          components: clippy, rustfmt
      - run: cargo build
      - run: cargo test
      - run: cargo test --features itoa
        working-directory: markup
      - run: cargo fmt -- --check
        if: ${{ matrix.os == 'ubuntu-latest' }}
      - run: cargo clippy --all-targets
